openapi: "3.0.0"
info: 
  title: "Question Service API"
  description: "This is the API for the Question Service. It describes the models it employs and data it returns"
  version: "1.0.0"
servers:
- url: https://question-service-develop.azurewebsites.net
  description: Development server
- url: https://question-service-master.azurewebsites.net
  description: Staging server
- url: https://question-service.azurewebsites.net
  description: Production server
paths:
  /questions/{questionId}:
    get:
      summary: "returns a question with the matching id"
      responses: 
        '200':
          description: the returned question
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Question'
        '404':
          description: A question with the specified ID was not found
    parameters:
      - name: "questionId"
        in: "path"
        description: "id of question to be found. This will be a kebab-case humar readable string"
        required: true
        schema:
          type: string
        example: 'a-hard-question'
  /questions:
    post:
      summary: "creates a new question"
      requestBody:
        description: parameters of the question to be created
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Pet'
      responses: 
        '201':
          description: the created question
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Question'
        '400':
          description: Bad request
          content:
            text/plain:
              schema:
                type: string
              examples:
                duplicate-question-creation-attempt:
                  summary: Error response for attempting to duplicate a question 
                  value: "Bad request: Question with id and title already exists"
                bad-request-body:
                  summary: Error response for incorrectly specifying the question to create 
                  value: "Bad request: Bad parameters in request body"
        '403':
          description: Forbidden
components:
  schemas:
    Question:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        body:
          type: string
        sampleAnswer:
          type: string
        successRate:
          type: number
          format: float
        difficulty:
          type: string
          enum:
            - easy
            - medium
            - hard
        solved:
          type: boolean
        hints:
          type: array
          items:
            type: string
        parentTopicTitle:
          type: string
        questionAnswerOptions:
          type: array
          items:
            type: string
