openapi: "3.0.0"
info: 
  title: "Question Service API"
  description: "This is the API for the Question Service. It describes the models it employs and data it returns"
  version: "1.0.0"
servers:
- url: https://question-service-develop.azurewebsites.net
  description: Development server
- url: https://question-service-master.azurewebsites.net
  description: Staging server
- url: https://question-service.azurewebsites.net
  description: Production server
paths:
  /questions/{questionId}:
    get:
      summary: "returns a question with the matching id"
      responses: 
        '200':
          description: the returned question
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Question'
        '404':
          description: A simple string response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ResourceNotFoundError'
    parameters:
      - name: "questionId"
        in: "path"
        description: "id of question to be found. This will be a kebab-case humar readable string"
        required: true
        schema:
          type: string
        example: 'a-hard-question'
components:
  schemas:
    ResourceNotFoundError:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Question:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        body:
          type: string
        sampleAnswer:
          type: string
        successRate:
          type: number
          format: float
        difficulty:
          type: string
          enum:
            - easy
            - medium
            - hard
        solved:
          type: boolean
        hints:
          type: array
          items:
            type: string
        parentTopicTitle:
          type: string
        questionAnswerOptions:
          type: array
          items:
            type: string
