openapi: "3.0.0"
info: 
  title: "Question Service API"
  description: "This is the API for the Question Service. It describes the models it employs and data it returns"
  version: "1.0.0"
servers:
- url: https://question-service-develop.azurewebsites.net
  description: Development server
- url: https://question-service-master.azurewebsites.net
  description: Staging server
- url: https://question-service.azurewebsites.net
  description: Production server
paths:
  /questions/{questionId}:
    get:
      summary: "returns a question with the matching id"
      responses: 
        '200':
          description: the returned question
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Question'
        '404':
          description: A simple string response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NotFoundErrorModel'
